### ISSUE TITLE
select color

### ISSUE THREAD

**Issue by hodanli** [g1eny0ung/logseq-github-theme#1]
hi,

thanks for the great theme. 

i think the color indicating selected blocks remained white for the light theme. 

best.

**Comment by g1eny0ung** [comment]
Good catch! 🤔 I'm doing wrong with this part. Following GitHub, I should render the selected blocks like this:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/15034155/159120672-0206f9ca-d932-445b-890b-73c75e1158b8.png">

**Comment by g1eny0ung** [comment]
Fixed in [28b69a8](https://github.com/g1eny0ung/logseq-github-theme/commit/28b69a8f2f4d3c2e11be60d2579ae2e4fec91704).
