### ISSUE TITLE
Issue with bullet threading plugin and SRS

### ISSUE THREAD

**Issue by pvlrmnnk** [g1eny0ung/logseq-github-theme#10]
<img width="838" alt="Screenshot 2022-05-27 at 13 10 10" src="https://user-images.githubusercontent.com/2040546/170679781-688db965-6f7b-4e46-9ee3-11a1ed108e4f.png">

**Comment by g1eny0ung** [comment]
Thanks for reporting this problem. To solve it, I revert the card style to default in [047e10f](https://github.com/g1eny0ung/logseq-github-theme/commit/047e10f73daaeda84ac6164b26977813e58939db).
