### ISSUE TITLE
Unable to overwrite font family and size

### ISSUE THREAD

**Issue by pztrn** [g1eny0ung/logseq-github-theme#12]
Using logseq 0.9.8, I'm unable to overwrite font family and size via `:root` tag as per [this suggestion](https://discuss.logseq.com/t/basic-ui-settings-e-g-font-size/2946/5). As I see you enforce fonts [here](https://github.com/g1eny0ung/logseq-github-theme/blob/main/sass/_common.sass#L31).

Can theme be fixed not to do that?

**Comment by g1eny0ung** [comment]
Yep. Seems the Logseq updates more, there has an `--ls-font-family` variable currently that can use to custom the font family. I will update the theme to suit the changes.

**Comment by g1eny0ung** [comment]
I found that Logseq has used the `Inter` font (https://github.com/logseq/logseq/blob/82cf4d3c65acbf230a3170640fe271dd74095067/resources/css/common.css#L8) and the github theme can safely omit the overwrite.

**Comment by g1eny0ung** [comment]
<img width="959" alt="image" src="https://github.com/g1eny0ung/logseq-github-theme/assets/15034155/662476c0-b21f-4070-96ec-791244fb9734">

I tested it in my local, and now it works fine.

**Comment by pztrn** [comment]
Thanks, confirming as working on my side!
