### ISSUE TITLE
block/page property BackgroundColor not styled in dark mode

### ISSUE THREAD

**Issue by dale502** [g1eny0ung/logseq-github-theme#2]

**Comment by g1eny0ung** [comment]
Can you provide a screenshot? I'm not quite sure if what you're describing matches what I think it does.

**Comment by dale502** [comment]
<img width="428" alt="image" src="https://user-images.githubusercontent.com/69394230/159202695-0aa354be-e04a-4406-8359-562d46daec89.png">
<img width="410" alt="image" src="https://user-images.githubusercontent.com/69394230/159202731-1ae1b153-eecf-4966-99c8-f2c20019024b.png">

**Comment by g1eny0ung** [comment]
Got it! I will resolve it soon.

**Comment by g1eny0ung** [comment]
Fixed in [8192e73](https://github.com/g1eny0ung/logseq-github-theme/commit/8192e7334241f32d1dc2fde07fcf61fa2b3e7a58).
