### ISSUE TITLE
Text display on mouse hover over a link is light on light in light mode and dark on dark in dark mode

### ISSUE THREAD

**Issue by apahl** [g1eny0ung/logseq-github-theme#4]
Hi, thanks a lot for this very nice theme, I like it a lot.  
I found one issue: it seems as if the text that is displayed when the mouse hovers over a link uses light text on a light background in the light theme and can therefore not be read (likewise dark text on dark bg is used in the dark theme):

![image](https://user-images.githubusercontent.com/9406836/162964656-eadfdd49-ef81-428d-bf98-ce95bba0d4ff.png)

Kind regards,  
Axel

**Comment by g1eny0ung** [comment]
Thanks for using it! ❤️ I tried but didn't reproduce this problem. Is this `folder` a page?

Or try a forced refresh? The shortcut is `Ctrl/Cmd + Shift + R`. Perhaps a forced refresh could resolve potential style conflicts.

**Comment by apahl** [comment]
Hi, thanks a lot for checking this out, the theme is really looking VERY nice!

`folder` is indeed a link to a local directory, you should be able to reproduce it with this text:

`([folder](/home/apahl/mydir/))`

(Refreshing or restarting Logseq did not change the behaviour.)

**Comment by apahl** [comment]
Ok, sorry, I just checked with the default Logseq theme and there the behavior is the same (text and bg color are the same).

So it seems, that this is actually not an issue with your theme, sorry for bothering you.  
Please feel free to close this.

KR Axel

**Comment by g1eny0ung** [comment]
Got it. I'll also see if I can fix this for Logseq.
