### ISSUE TITLE
样式在指令选项下有问题

### ISSUE THREAD

**Issue by cctga** [g1eny0ung/logseq-github-theme#5]
你好👋，亲爱的开发者，我非常喜欢你设计的样式，但我发现他在这里有一个小问题，虽然它无伤大雅，但是我希望它能得到修正，非常感谢你
<img width="848" alt="image" src="https://user-images.githubusercontent.com/12812919/164449793-7be87af6-9364-488e-9594-2d053cdeaa02.png">

按下 command+shift+p 可以展示出指令选项

logseq 版本：0.6.6
系统：macOS Monterey m1

**Comment by g1eny0ung** [comment]
❤️ 感谢指出。这个问题已修复。
