### ISSUE TITLE
Can the `todo` block's color be changed

### ISSUE THREAD

**Issue by mendax1234** [g1eny0ung/logseq-github-theme#6]
![image](https://user-images.githubusercontent.com/62934294/169695558-0d5ef6a1-59d5-429c-b3ad-c2efc360c91b.png)
l think the color of the 'todo'task is not very comfortable. Can you change it?

**Comment by mendax1234** [comment]
l think it can be changed to this one.
![image](https://user-images.githubusercontent.com/62934294/169722696-3583a672-2987-4f31-b921-096a2def98a3.png)

**Comment by mendax1234** [comment]
Since in Github, the green is the most used color,
![image](https://user-images.githubusercontent.com/62934294/169722736-4e3d6dad-7df6-4ec2-886a-8366c9d9f1d9.png)
So, l think the color green is better. Hope this function can be added!

**Comment by g1eny0ung** [comment]
I've already seen #7, but we can discuss it here first. I agree with you, the color of the `TODO` should be changed.

Logseq has three task states, `TODO`, `DOING`, and `DONE`. The mapping of them on GitHub I think can be represented by the three states of PR, `Draft`, `Open`, and `Closed`.

So refer to https://primer.style/primitives/colors, the `TODO` color should be updated to `neutral.emphasis`. If you agree with this, I will update it later. Thanks so much for pointing out this problem. ❤️

**Comment by g1eny0ung** [comment]
BTW, #7 should update the sass file instead of the CSS file. CSS is compiled from sass. But that's okay, I can handle the code changes needed for this issue.

**Comment by mendax1234** [comment]
> I've already seen #7, but we can discuss it here first. I agree with you, the color of the `TODO` should be changed.
> 
> Logseq has three task states, `TODO`, `DOING`, and `DONE`. The mapping of them on GitHub I think can be represented by the three states of PR, `Draft`, `Open`, and `Closed`.
> 
> So refer to https://primer.style/primitives/colors, the `TODO` color should be updated to `neutral.emphasis`. If you agree with this, I will update it later. Thanks so much for pointing out this problem. ❤️

I agree with you! Hope this can be changed soon!

**Comment by mendax1234** [comment]
But , l think red is too irritative in the dark mode. How does Github deal with it?

**Comment by g1eny0ung** [comment]
> But , l think red is too irritative in the dark mode. How does Github deal with it?

What does this refer to?
