### ISSUE TITLE
Problems with the checkbox in `All pages`

### ISSUE THREAD

**Issue by mendax1234** [g1eny0ung/logseq-github-theme#8]
The blocks in the `All page` in the dark mode is invisible. It is all dark!
l change the line below.
![image](https://user-images.githubusercontent.com/62934294/170068139-9331546f-4520-43fb-a98c-2e2dd43cdfc8.png)
And it is the effect
![image](https://user-images.githubusercontent.com/62934294/170068049-6a8c0934-bf08-4de1-ac6c-05c18fc06688.png)
Hope this can be fixed!

**Comment by g1eny0ung** [comment]
🤔 I didn't find anything strange. What did it look like before the modification?

**Comment by mendax1234** [comment]
![image](https://user-images.githubusercontent.com/62934294/170148276-a574b05b-e326-4dc0-b2f2-182eb690e2fb.png)
Like above.

![image](https://user-images.githubusercontent.com/62934294/170148301-351712b2-203a-42f2-8c2e-822d8c7bb27d.png)
And the block in front of the `Contents` is invisible. So do all other pages. @g1eny0ung

**Comment by mendax1234** [comment]
Besides , when will the new version be released? @g1eny0ung

**Comment by mendax1234** [comment]
@g1eny0ung If this also wants to be like Github. I think it should like below
In the light mode:
![image](https://user-images.githubusercontent.com/62934294/170157083-a372d561-53b4-4349-8fc2-891227772704.png)

In the dark mode:
<img width="743" alt="image" src="https://user-images.githubusercontent.com/62934294/170157169-8459fb27-8481-4a45-a7bb-e7a8790c372a.png">

**Comment by g1eny0ung** [comment]
Got it! I know you mean. The checkboxes don't look too obvious, so I'll modify them.

**Comment by g1eny0ung** [comment]
> Besides , when will the new version be released? @g1eny0ung

Actually, Logseq doesn't depend on whether a repo is released or not. You can just click `check for updates` on the UI to update a theme to the latest version.

**Comment by g1eny0ung** [comment]
@mendax1234 After my investigation, I found that GitHub didn't follow the [Primer](https://primer.style/) design system on the checkbox. They use the default style without any modifications on it.

So I'm keeping the checkbox style consistent with checkboxes like the one here at https://primer.style/react/SelectPanel in [82bd69f](https://github.com/g1eny0ung/logseq-github-theme/commit/82bd69f267c5b8a6c8f78ac614a9dc3eadd7e428). You can update the theme to see the effect.

**Comment by mendax1234** [comment]
>Actually, Logseq doesn't depend on whether a repo is released or not. You can just click check for updates on the UI to update a theme to the latest version.

If you don't release a new version in the `Releases`, l can not get the latest version by using logseq's `check the update`
You should release a new version in the `Releases`
![image](https://user-images.githubusercontent.com/62934294/170388807-0227b198-e7c1-40e1-8a5d-305905513039.png)
Thanks! @g1eny0ung

**Comment by g1eny0ung** [comment]
🤔 Really? Anyway, I will release a version soon.

**Comment by mendax1234** [comment]
Thanks!

**Comment by g1eny0ung** [comment]
Released. https://github.com/g1eny0ung/logseq-github-theme/releases/tag/v1.2.0

**Comment by mendax1234** [comment]
@g1eny0ung It seems that this bug is not fixed at all.
![image](https://user-images.githubusercontent.com/62934294/170450617-dca49780-f945-4524-9747-7a54d5f5f3dc.png)

**Comment by mendax1234** [comment]
l still can't see anything in the dark mode....

**Comment by g1eny0ung** [comment]
> l still can't see anything in the dark mode....

Here I explained why: https://github.com/g1eny0ung/logseq-github-theme/issues/8#issuecomment-1137663930. I can't reset the `checkbox` to a bare state. 😢 This is a limitation of css itself (You can't remove a class that has already been set). So I had to follow the Primer design.

**Comment by g1eny0ung** [comment]
You can modify it to meet your needs further via `custom.css`.

**Comment by mendax1234** [comment]
How to do that?

**Comment by mendax1234** [comment]
Besides , l think l should make a new theme based on yours. But l don't know how to do it? Can you give me some tips? For example , to make a theme, besides a css,  what files should l need? @g1eny0ung

**Comment by g1eny0ung** [comment]
Edit this file to override styles:

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/15034155/170463341-b30f1f28-8452-454f-9a59-b77e808cd76e.png">

**Comment by mendax1234** [comment]
So, what should l add?

**Comment by g1eny0ung** [comment]
> So, what should l add?

This depends on what you want. For example a more saturated `border-color`. If what you want to know is how to override styles, I think you need additional knowledge about css selectors.

**Comment by mendax1234** [comment]
So, what does you `sass` do?
